sonar.projectKey=caderno
sonar.projectName=Caderno
sonar.projectVersion=1.0

# Fontes Dart/Flutter
sonar.sources=lib
sonar.tests=test

# Exclusões comuns
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.gr.dart,build/**,ios/**,android/**,web/**

# Cobertura de testes (opcional mas recomendado)
# sonar.dart.lcov.reportPaths=coverage/lcov.info